### ISSUE TITLE
Build failing on iOS

### ISSUE THREAD

**Issue by andrewdang17** [honeybadger-io/honeybadger-react-native#38]
I cannot get a build to work after installing version `0.0.11` on iOS. I'm on react-native `0.67.2` and after `npm install` and `npx pod install` I get these errors from the `npx react-native run-ios` command

```
The following build commands failed:
	CompileC /Users/andrew/Library/Developer/Xcode/DerivedData/mobile-edwrdfxbkmonuxehfsupzmpbmpqe/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/HoneybadgerReactNative.build/Objects-normal/x86_64/HoneybadgerReactNative.o /Users/andrew/soundstripe/mobile/node_modules/@honeybadger-io/react-native/ios/HoneybadgerReactNative.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'HoneybadgerReactNative' from project 'Pods')
(2 failures)
```

Here's more indepth errors from xcode:

<img width="802" alt="Screen Shot 2022-09-01 at 9 14 35 AM" src="https://user-images.githubusercontent.com/9098711/187963780-b2d48b95-3331-43a9-a023-3b209feca961.png">

**Comment by andrewdang17** [comment]
I also tried creating a new RN app (using the [ignite boilerplate](https://github.com/infinitered/ignite)) and could not get it working either. It results in the same build error with RN 0.68.2

**Comment by andreybutov** [comment]
@andrewdang17 Can you run through these steps in a clean directory and let me know if it works:

```
npx react-native init TestProject
```

If you get a "failed to install cocoapods dependencies", run the following to force RN to install cocoapods properly:
```
cd ./TestProject/ios
pod install
```

Once the above is done:
```
npm install "@honeybadger-io/react-native"
cd ios
pod install
```

Then to start:
```
npx react-native start
npx react-native run-ios
```

**Comment by andrewdang17** [comment]
@andreybutov Thanks for the quick reply. I was able to build which means it must have something to do with the [ignite boilerplate](https://github.com/infinitered/ignite)

**Comment by andreybutov** [comment]
@andrewdang17 I ran the above steps with the a fresh install of the latest version of React Native (0.69.5), and with a fresh install of your reported version (0.67.2). Both worked without error. If you had previously used the command npx react-native install "@honeybadger-io/react-native" to install the package, that no longer works (the docs have been updated), but you would have seen a different error. So, my current assumption is that it's either the ignite boilerplate (which I've yet to try), some issue with your machine architecture (M1, etc), or something in the environment. Since the above steps worked with both your version of RN and the latest, I suggest you go with those. I will try the ignite boilerplate to see what's going on there.

**Comment by andrewdang17** [comment]
@andreybutov thanks, appreciate you looking into it! I'm on a non M1 macbook and I had a coworker with an M1 try and we got the same build error so we can rule that out. I believe it is the ignite boilerplate as he could not get it working there either. Also I doubt that this would be the issue but I am using `yarn` and not `npm`.

**Comment by andreybutov** [comment]
@andrewdang17 I will take a look at ignite to see if I can resolve this.

**Comment by andreybutov** [comment]
@andrewdang17 The Honeybadger RN library has been patched to work with Ignore. Grab version 0.0.12 from npm or GitHub. 

The following clean ignite installation worked for me with 0.0.12

```
npx ignite-cli new TestApp
cd TestApp
yarn add "@honeybadger-io/react-native"
yarn run ios
npx react-native start
npx react-native run-ios

```

**Comment by andrewdang17** [comment]
@andreybutov thanks!! 🙏
